### ISSUE TITLE
Shallow clone flag not working

### ISSUE THREAD

**Issue by MrLuje** [meaningful-ooo/devcontainer-features#50]
I'm not sure why and pretty sure it was working last time I used it but the following configuration is doing a full clone :
```json
	"features": {
		"ghcr.io/meaningful-ooo/devcontainer-features/homebrew:2": {
			"shallowClone": true,
			"version": "2.0.3"
		}
    }
```

Got around it by setting the env var at the end of the Dockerfile 🤷‍♂️ 
```dockerfile
ENV SHALLOW_CLONE="true"
```

Note: I'm prebuilding the image with `npx @devcontainers/cli build` but I don't think it change the issue

**Comment by eitsupi** [comment]
Thanks for reporting this. I think this is due to a typo.

https://github.com/meaningful-ooo/devcontainer-features/blob/a10044f2ac392aca06fff212267a21eb6d8376a2/src/homebrew/install.sh#L4

This line should be `SHALLOW_CLONE=${SHALLOWCLONE:-"false"}`

@MrLuje Could you create a PR to fix this?

**Comment by MrLuje** [comment]
Sure, thanks for looking at it
