### ISSUE TITLE
fisher should be installed.

### ISSUE THREAD

**Issue by Bzybree92** [meaningful-ooo/devcontainer-features#61]
fisher should be installed.

```suggestion
if [ "${FISHER}" = "true" ] && [ -n "${FISHERPLUGINS}" ]; then
```

_Originally posted by @eitsupi in https://github.com/meaningful-ooo/devcontainer-features/pull/25#discussion_r1016460435_

**Comment by eitsupi** [comment]
This issue seems created by mistake.
